### ISSUE TITLE
Make --checkconfig check for existence of input directories

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#169]
This would be very useful.

**Comment by MarcusBarnes** [comment]
@mjordan I needed a quick win.  An initial go at addressing this issue is located in https://github.com/MarcusBarnes/mik/tree/issue-169  It should be tested on Windows.  Use is similar to other checks by using option `--checkconfig=all` or for just the input_directories paths, using the option `--checkconfig=input_directories`  @mjordan: if you are happy with the code, please create a pull-request and merge at your convenience.

**Comment by mjordan** [comment]
Works as expected, closing.

**Comment by MarcusBarnes** [comment]
@mjordan Thank you.
