### ISSUE TITLE
Commas in <null> field cause crash

### ISSUE THREAD

**Issue by GarrettArm** [MarcusBarnes/mik#200]
In a mappings_file, if the static field in a line contains a comma, it crashes mik.  

null4,<location>Library, 3rd Flood</location>

Problem is just around line 75 in CdmToMods.php where $this->collectionMappingArray is a 2-element array for all pairs, except null4.  Null4 is a 3-element array.  I suspect it is incorrectly parsed.

For a temporary work-around, I've removed all commas from that field in my mappings_files and replaced them with colons.

**Comment by MarcusBarnes** [comment]
@GarrettArm Thank you for your feedback.  As you discovered, because the comma is the field separator in your mappings CSV file, your snippet would be interpreted as having three values, not two as you desired.  Changing the default field separator character will work, assuming that you don't have another mapping with a colon in the field value.    What is often done is to put double-quotes like this:

null4,"\<location\>Library, 3rd Flood\</location\>"

This should be parsed as two CSV field not two.   I personally like to escape all fields and use single quotes for attribute values inside the CSV field values.  

Just in case you haven't seen the wiki page on the mappings file, I'm including the link here: https://github.com/MarcusBarnes/mik/wiki/The-mappings-file

**Comment by MarcusBarnes** [comment]
@GarrettArm @mjordan For the 1.0 milestone, one possible enhancement to the checks on the mappings file that would be to verify that each row has the same number of fields to help avoid such issues. The format for MIK mappings files assumes that each row will have the same number of fields (even if they are empty).  Currently, running MIK with --checkconfig=snippets does not appear to detect this.

**Comment by mjordan** [comment]
:+1:  to adding a check that the mappings file has the expected number of columns.

**Comment by mjordan** [comment]
@MarcusBarnes we do this in `--checkconfig` for the CSV input file. I can add similar code to do it for the mappings file.
