### ISSUE TITLE
Make the date.timezone PHP setting in MIK a configuration option

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#215]
We've hard coded 'America/Vancouver' but this will, obviously, be different for others.

**Comment by MarcusBarnes** [comment]
@mjordan I'll address this now.  Thanks.

**Comment by mjordan** [comment]
@MarcusBarnes just a reminder that all settings in the `[CONFIG]` section are added to the mik.log. Maybe we should introduce a `[SYSTEM]` section for this sort of thing?

**Comment by MarcusBarnes** [comment]
@mjordan Thank you for the reminder.  Though it may be useful to know which timezone was used for the logging timestamps in some cases, the main reason for including this is that a timezone value for date.timezone is required for monolog to work.   This provides a work-around should date.timezone not be set in the PHP.ini where MIK is run.

The expected behavior is to use [SYSTEM][date_default_timezone] if it is set in the config or use the value from the PHP.ini.  If date.timezone is not set in the PHP.ini and no [SYSTEM][date_default_timezone] is set in the MIK configuration file for the given collection, default to 'America/Vancouver'.

This issue is addressed in pull-request https://github.com/MarcusBarnes/mik/pull/217.

**Comment by mjordan** [comment]
PR merged.
