### ISSUE TITLE
Potential problem with mapping source field labels that contain hyphens

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#232]
We've discovered an instance where a mapping from a CONTENTdm field name that contained a hypen didn't work - all resulting MODS documents had an empty target element. The row from the mapping file is:

`Series-group,"<relatedItem type=""series""><titleInfo><title>%value%</title></titleInfo></relatedItem>"`

We need to test to see if the hyphen may have caused the problem of it was caused by something else. For example, would putting the source field label in quotation marks have an effect? If there is a problem, is it specific to the CONTENTdm toolchains or does it also occur with CSV toolchains?

**Comment by mjordan** [comment]
@MarcusBarnes if you have time to test this I'd appreciate it, if not I can.

**Comment by MarcusBarnes** [comment]
@mjordan I'd like to test.  Would you send me some additional material so that I can test?  Thank you.

**Comment by mjordan** [comment]
@MarcusBarnes will do.

**Comment by MarcusBarnes** [comment]
@mjordan I've confirmed the issue, but it's related to wrapper element code in CdmToMods.php metadata parser rather than an issue with the source field containing a hyphen.   To confirm this, one can add the `repeatable_wrapper_elements[] = titleInfo` under the `[METADATA_PARSER]` section of the configuration file.  Wrapper element code doesn't adequately deal with top-level elements that are children of other top-level elements.  I'm going to close this issue  and open another issue that better documents the problem.
