### ISSUE TITLE
CSV: Multiple problems for records with no file

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#294]
In the CSV toolchain, multiple issues crop up if you have records with no associated file. (This assumes that you do want XML files generated for records without files -- we do.)

1. Filename column exists, record has nothing in that field:
MIK creates one XML file, named after the input directory (e.g. kora_files.xml). If there are multiple records with nothing in the filename field, only one XML file is generated.

2. Filename column doesn't exist, but file_name_field is defined: 
No XML files are generated. Multiple errors in mik.log. Example error:
`[2016-11-23 22:24:42] ErrorException.ERROR: ErrorException {"message":107,"code":{"metadata":"<?xml version=\"1.0\"?>\n<mods xmlns=\"http://www.loc.gov/mods/v3\" xmlns:mods=\"http://www.loc.gov/mods/v3\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n  <titleInfo>\n    <title>#JewsandArabsrefusetobeenemies</title>\n  </titleInfo>\n  <subject>\n    <topic>Social and Behavioral Sciences</topic>\n  </subject>\n  <subject>\n    <topic>Sociology</topic>\n  </subject>\n  <abstract>What happens when you bring two people to discuss the most complex conflict of the century, the Palestinian Israeli conflict? What about if these two individuals are a Palestinian and an Israeli? Driven by their commitment for conflict resolution, peace, and recognition of the other, Saed Abu-Haltam and Maria Goldin, Palestinian and Israeli KPU students, respectively, have been regularly discussing the conflict and looking for ways to explore common beliefs and unshakeable differences. However, with the right environment and inspiring personal stories, their lives have transformed and led them to understand and value the legitimacy of the other. At KPU&#x2019;s Sociology and Criminology conference, Saed and Maria will put forward ideas and strategies that they think are crucial to achieving peace in the region and in their states. And yes, that means that they both believe peace is possible!</abstract>\n  <identifier type=\"uri\" invalid=\"yes\" displayLabel=\"Migrated from\">http://kora.kpu.ca/scusc/scusc_2014/schedule/1</identifier>\n  <name type=\"personal\">\n  <namePart type=\"given\">\n\tSaed\n  </namePart>\n  <namePart type=\"family\">\n    Abu-Haltam\n  </namePart>\n    <role>\n    <roleTerm authority=\"marcrelator\">author</roleTerm>\n  </role>\n      <nameIdentifier type=\"email\">Saed.abuhaltam@kwantlen.net</nameIdentifier>\n  \n      \t<affiliation>Kwantlen Polytechnic University</affiliation>\n   \n</name>\n  <originInfo>\n\t<dateIssued keyDate=\"yes\">2014-11-07</dateIssued>\n\t\t</originInfo>\n</mods>\n\n","pages":[],"record_id":"1","no_datastreams_setting_flag":true,"preserve_content_filenames":"1","output_path":"/tmp/kora_output/scusc_event/","source_file_path":"/Users/Brandon/mik/kora_files/","source_file_name":"kora_files","source_file_extension":"","identifier":"kora_files","content_file_path":"/tmp/kora_output/scusc_event/kora_files.","metadata_file_path":"/tmp/kora_output/scusc_event/kora_files.xml","enforce_metadata_only":false,"MODS_expected":false,"DC_expected":false},"severity":2,"file":"copy(): The first argument to copy() function cannot be a directory","line":"/Users/Brandon/mik/src/writers/CsvSingleFile.php"} []`

3. If filename column doesn't exist, and file_name_field is not defined:
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /Users/Brandon/mik/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php on line 82`

**Comment by bondjimbond** [comment]
#1 is the really strange one, which I would classify as a bug. 

For 2 and 3, it would be useful to throw up an error like "file_name_field not defined" or "file_name_field not present" to assist in troubleshooting.

**Comment by bondjimbond** [comment]
More info re number 1: The resulting XML file contains only the data from the last row in the CSV. 

Hypothesis: each row is processed, but is written to the same file name each time, so only the final row's XML file is present.

Possible solution: logic that appends the key field's content (e.g. 1, 2, etc) to the XML filename?

**Comment by mjordan** [comment]
@bondjimbond problem 1 is clearly a bug. We (SFU) didn't forsee not having a value in that field and intended that if the source file could not be found (it was misnamed, etc.) we'd want MIK to log that fact and to move on to the next entry in the CSV file, and not create a MODS-only package. If we want to support both use cases (if no source file, then don't create an Islandora package, and if no source file or if field is empty, create a MODS file), we need a config option (something like `[WRITER] require_source_file` to allow the user to select the desired behaviour. I think this change should be identified a separate issue, which I will open once I hear some feedback on this approach from you and @MarcusBarnes. I'd be happy to take on the work of adding this option to the CSV Single File toolchain but having just gone through https://github.com/MarcusBarnes/mik/pull/289 I can't commit to doing it for books, newspapers, and compound at the current time.

A workaround for this problem is to generate only MODS files but adding `MODS` as the only datastream ID to `[WRITER datastreams[]` as documented at https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Generating-metadata-only,-not-content-files. Of course, you would have to run MIK twice, once with the option absent and then once with it present.

Problems 2 and 3 should never arise, since the `[FILE_GETTER] file_name_field` setting is documented as required. At most we should add a check for required fields in `--checkconfig`. I'll look into that and open a new issue.

**Comment by bondjimbond** [comment]
Thanks, Mark... here's a set of thoughts on this:

Running MIK twice - once for records with files and once for records without - would not be the hoped-for solution, but I could accept it as a workaround. In a typical CSV dump of objects from a repository, there's a mix of objects with files and objects that are metadata-only. Would this mean that the MODS files for objects with files are generated twice?

Re problem 2: This certainly could arise naturally, as it did for me -- one of our CSVs came from a collection that is entirely citation-only, so there was no column to contain the filename. The file_name_field was defined, but the field didn't actually exist in the CSV - so errored out. I had to insert my filename column with empty rows to avoid the error. The check function on the CSV looking for the presence of the column defined in file_name_field would be good.

**Comment by mjordan** [comment]
I mention the workaround because it will work today. But it's still a workaround. Thanks for offering the use case of not having a file but wanting a MODS file.  In the workaround, MODS files for objects with files would be generated twice, but that shouldn't be a problem since the twice-generated files should be identical. Or, you could output the MODS for each run of MIK into different output directories, which would avoid overwriting the ones for objects that have files.

Re problem 2, what I meant was that the field needs to be defined in the .ini *and* it needs to exist in the CSV. If we allow blank values (problem 1), we should be good to go, should we not?

**Comment by bondjimbond** [comment]
Yep, I think so. So what's going on with kora_files.xml then? It looks like it actually is generating XML and saving it for blank fields, but it's either only doing it for the last one, or it's doing it over and over again with the same filename.

**Comment by bondjimbond** [comment]
Another file_name_field error comes up in #296.

**Comment by bondjimbond** [comment]
Re the workaround to generate only MODS:
As directed, set:
`[WRITER]
datastreams[] = MODS`
Ran MIK on a CSV with 50 records, each with no file. Same problem crops up. Only a single file, [input_directory name].xml, is created.

Confirm that the code above does generate xml-only files as expected; tried running a CSV with seven records - 6 with file, 1 without. Created six XML-only records named for filenames, and one named kora_files.xml. But it fails to accommodate records that have no file to reference.

**Comment by bondjimbond** [comment]
To see if the single-XML-file problem was tied to a config setting, tried commenting out `preserve_content_filenames = true`, but this generated an error:

> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 78 bytes) in /Users/Brandon/mik/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php on line 77

**Comment by mjordan** [comment]
Try with `[FILE_GETTER] input_directory =` (i.e., an empty value) with MODS as the only value for `datastreams[]`. Just recently added feature.

**Comment by bondjimbond** [comment]
Even worse -- same file, now just called ".xml" which defaults to being a hidden file.

**Comment by mjordan** [comment]
Are you on a recent pull (within last two days) of master branch? Also, at this point blank values for whatever field is defined in `[FILE_GETTER] file_name_field` are not allowed (to be fixed with work on https://github.com/MarcusBarnes/mik/issues/296).

**Comment by bondjimbond** [comment]
Yes, I pulled yesterday and again after you merged the fix for #293. 

Sorry, Mark - maybe I'm not clear on what you're asking me to try. Which problem is this workaround intended to fix, if I can't have blank fields for the filename?

**Comment by mjordan** [comment]
Yeah- things are changing pretty fast. The combination of `[FILE_GETTER] input_directory =` and `[WRITER datastreams[] = MODS` was supposed to let you generate MODS files without having any input files as described in #284.

**Comment by bondjimbond** [comment]
Right; that's the setup I put in my .ini file, which does not behave as intended.

Just to be clear -- it IS generating MODS files anyway, whether or not you make the changes you suggest. The problem is that it only generates one MODS file for the whole CSV (or rather, for all entries that have an empty value in the file_name_field). My suspicion is that this is simply a case of MIK failing to change the filename for each subsequent record with empty value.

If we're still not on the same page about this, maybe we should meet at 2 as you'd originally suggested so I can demonstrate?

**Comment by mjordan** [comment]
Sure, I'm out of my meeting now and can meet - but currently, MIK doesn't know how to deal with empty file field values. Work against #297 will address this.

**Comment by bondjimbond** [comment]
I think the merging of #297 closes this issue.
