### ISSUE TITLE
CSV single file toolchain: Error not logged when file doesn't exist

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#296]
When a filename is present in the file_name_field, but the file referenced is not actually present in the input_directory, the following happens:

- No package is created for that record
- The failure is not logged in mik.log, nor in problem_records.log

The net result of this is that neglecting to include a file in the input_directory could mean unnoticed loss of records in a migration.

Related issues with file_name_field in #294.

**Comment by mjordan** [comment]
"The failure is not logged in mik.log, nor in problem_records.log" qualifies this as a bug since the intended behavior is to log it.

**Comment by mjordan** [comment]
I just tried to confirm this bug and could not. By removing a file named in my `file_name_field` and running MIK, I do get the following entry in my mik.log:

`[2016-11-24 12:35:17] writer.WARNING: Source file does not exist, skipping writing package {"source_file":"/home/mark/Downloads/mik_csv_no_file_input/IMG_2958.JPG"} []`

and no MODS file corresponding to the missing image was generated. You are correct that no entry is added to problem_records.log, but looking at an example of the mik.log entry now I recall that is by design since the mik.log entry is only a warning, not an error or an exception. @MarcusBarnes should probably confirm my understanding of what gets logged in problem.log.

The mik.log can be pretty hard to interpret, since it is where a wide range of message go, including everything from warnings like this one to full scale debug barfs when things go crazily off the rails. In fact during the migration of our newspapers from CONTENTdm we split mik.log out from problem_records.log on the advice of @kbolko to make it easier to spot objects that failed catastrophically.

I recommend adding a cookbook entry that points out the kinds of things to look for in mik.log, and link to it under the Troubleshooting section of https://github.com/MarcusBarnes/mik/wiki/The-MIK-Cookbook. Included in this entry should be clear explanation of the relationship between mik.log and problem_records.log, and where applicable, the manipulators.log. @bondjimbond would you be willing to take a look at drafts of this entry?

**Comment by bondjimbond** [comment]
> [2016-11-24 12:35:17] writer.WARNING: Source file does not exist, skipping writing package {"source_file":"/home/mark/Downloads/mik_csv_no_file_input/IMG_2958.JPG"} []

Right - now that I look for this, I can find it too. I was thrown off because all the other entries in mik.log reference the key field - this one doesn't, so I couldn't find it. problem_records.log also references the key field, which makes it seem like this is how you should be looking for these things.

> You are correct that no entry is added to problem_records.log, but looking at an example of the mik.log entry now I recall that is by design since the mik.log entry is only a warning, not an error or an exception. 

I'd call the failure to find a file and therefore not creating a record a pretty clear candidate for the problem_records.log. Certainly, given the length and complexity of mik.log, this is the only way you'd really be able to know which packages failed to get created.

Sure, I'd be happy to look at any drafts of this cookbook entry - but I'd argue that this is not a documentation problem. At least from my perspective, any record in the CSV that is not turned into a package should be logged as a problem record.

**Comment by mjordan** [comment]
Thanks for pointing out that the record key is not logged - it should be. I'll fix that and open a PR for it. When you respond to #297 would you mind indicating that if a package is skipped and `[WRITER] require_source_file` is true that it be logged in problem_records.log? I'd still like to hear @MarcusBarnes recollection of what currently triggers an entry in problem_records.log however, just so we have context. If an exception is the trigger, we may want to implement not writing package as an exception, for example.

**Comment by mjordan** [comment]
On second thought, adding the record key to the mik.log entry can be done at the same time as work on #297.

**Comment by MarcusBarnes** [comment]
@mjordan My recollection was that any problem that would cause a package to fail should be logged to the problem_records.log.  Then the problem can be investigated (it's not just a warning, but an error that needs investigation).  Once the problem has been resolved, a list of keys/pointers can be extracted using a script like the [specific set from problem records script](https://github.com/MarcusBarnes/mik/blob/master/extras/scripts/specificsetfromproblemrecords.php) for use with the [SpecificSet fetcher manipulator](https://github.com/MarcusBarnes/mik/blob/master/src/fetchermanipulators/SpecificSet.php).  We should double check how the CdmNewspaper writer handles the case when an expected file cannot be found, as the problem_records.log was very useful when using that toolchain.

**Comment by mjordan** [comment]
Thanks, I'll check the CdmNewspapers toolchain. Adding an entry to problem_records.log for any package that was not generated sounds like a reasonable guideline, and is consistent with @bondjimbond's argument above.

**Comment by mjordan** [comment]
@MarcusBarnes In my local working branch for this issue I have records skipped due to missing input files logging to problem_records.log. To do this, I instantiated a "problemLog" object in the base Writer class, paralleling the "log" object we've always had. The CsvSingleFile writer writes these entries with the following code:

```php
 $this->problemLog->addError("Source file not found, skipping writing package",
     array('record ID' => $record_id, 'source file' => $source_file_path));
```

This $writer->problemLog object is completely separate from the exception logging that happens within the mik script. For example, the path to the log is defined directly within mik, and I'm defining it in my new $writer->problemLog object to use the same path.

I'd like to propose that as part of the 1.0 milestone we revisit how we're writing to the problem log, perhaps pushing all logging through a single problemLog object instantiated in one place such as the existing Config class or a new Logger class. To move forward on the current issue I'll use the new problemLog object I've added to the base Writer class, but do you think we should open a new issue to discuss a centralized problem logger, and maybe along with it a centralized warning logger, as described here?

**Comment by mjordan** [comment]
Note for later - the regex at https://github.com/MarcusBarnes/mik/blob/master/extras/scripts/specificsetfromproblemrecords.php#L52 only catches numbers. Once this all settles we'll need to update it to pick out any type of `record_id` values.

**Comment by MarcusBarnes** [comment]
@mjordan A new issue would be appropriate to discuss a broader change in how we're handling various logging activities.  Thank you for the suggestions and for pointing out that the helper script in the extras folder should be updated to accommodate any type of `record_id` value.

**Comment by mjordan** [comment]
OK, will do.

**Comment by mjordan** [comment]
Fix to this has been merged - any objections to closing?

**Comment by bondjimbond** [comment]
I'm good.
