### ISSUE TITLE
Allow blank entries in file name field for CSV single file toolchain

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#297]
This issue comes out of #294. Summary of relevant discussion:

Currently MIK skips creation of a MODS file if the corresponding PDF, etc. named in the field identified in `[FILE_GETTER] file_name_field` is not found. However, in some cases it is desirable to generate a MODS file even though there is no corresponding PDF, etc. In these cases, the file name field may contain an empty value because the file is known to not exist.

To accommodate both use cases, we will need to add a .ini option to allow or disallow creation of MODS files for rows in the CSV input file where the specified PDF is not found, or where there are blank values in the field identified in `[FILE_GETTER] file_name_field`. I recommend adding the `[WRITER] require_source_file` option with a default of `false`; users who want MIK to skip creation of the MODS file will need to set this option to `true`.

@bondjimbond and @MarcusBarnes please let me know your thoughts on this proposal.

**Comment by bondjimbond** [comment]
To clarify the two use cases above:

1. If file is referenced in file_name_field but is not found in the input_directory, package creation gets skipped. This is not currently logged in problem_records.log - it should be. (Additionally, the entry that is created in mik.log fails to include the key field, making it even harder to identify.)

2. If the file_name_field contains an empty value, a MODS XML file should be created anyway. This should be optional.

For the **second** use case, I'm very happy with the suggestion `[WRITER] require_source_file` defaulting to false so that MODS files are created. 
NOTE that the filename needs to be given consideration - presently, a file is created but is overwritten by each subsequent record with an empty value in the file_name_field. I'd suggest at very least including the key field value in the filename to ensure uniqueness.

For the **first** use case, I'd say that the suggested `[WRITER] require_source_file` option shouldn't matter, whether true or false. This is a clear case of a problem record, and MIK needs to flag it as such. Since problem records don't generate packages in all other cases, this should be no exception.

**Comment by mjordan** [comment]
I think this is ready to test:

* Empty values in field defined in `[FILE_GETTER] file_name_field` are now allowed in the input fie for the CSV Single File toolchain
  * Rows whose file name field are empty will get a MODS file named after the record_id
* The new .ini option `[WRITER]require_source_file` determines whether packages are created for rows whose file name field is empty; if set to false (the default), they are; if set to true, they are skipped and  reported in both mik.log and problem_records.log
* A file referenced in file name field that cannot be found, regardless of the value of `[WRITER]require_source_file`, is skipped and  reported in both mik.log and problem_records.log.

@bondjimbond if you could test this in the issue-297 branch and report back, I'd appreciate it.

**Comment by bondjimbond** [comment]
Tested a 50-record CSV with blank entries in the filename field. Expecting 50 XML files labeled 1.xml to 50.xml.

Test 1:
```
input_directory =
datastreams[] = MODS
```
Result: 50 good XML files.

Test 2: 
`input_directory =` WITHOUT `datastreams[] = MODS`
Result: 50 good XML files.

Test 3:
`input_directory = "/Users/Brandon/mik/kora_files"` 
Result: 50 good XML files.

Conclusion: It works! But the special configurations (`input directory =`, `datastreams[] = MODS`) appear to be unnecessary.

**Comment by bondjimbond** [comment]
Testing bad filenames:

Test 4: Garbage entries in the file_name_field, each with unique file names.
Result: 50 entries in problem_records.log.

Test 5: Garbage entires in file_name_field, all identical.
Result: 50 entries in problem_records.log.

Conclusion: It works.

**Comment by bondjimbond** [comment]
I think we're ready for a pull request - but may need to review the case for `input_directory =`. And `datastreams[] = MODS` is not needed in this case.

**Comment by mjordan** [comment]
@bondjimbond sweet, thanks. With great functionality comes great configuration bloat. I'll take a crack at updating the docs for all of this and ask you to take a look if that's OK.

@MarcusBarnes I'll open a PR and once you've merge it, move on to updating the documentation.

**Comment by mjordan** [comment]
@bondjimbond  `input_directory =`. And `datastreams[] = MODS` still applies if I am testing on a laptop with no access to the source files. Plus, the other three CSV toolchains can use the same pair of configuration options. I'd rather retain these options for the CSV Single File toolchain and maybe add some scenarios to https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Generating-metadata-only,-not-content-files.

**Comment by bondjimbond** [comment]
I should add that in my testing I neglected to include the new require_source_file option. Will test now.

**Comment by bondjimbond** [comment]
Test: 50 blank filenames, set `require_source_file = true` 
Result: No XML, 50 problem record entries. Good to go!

**Comment by bondjimbond** [comment]
Final test: a CSV with 7 records - six with files, one without. Result: all processed as expected.

**Comment by mjordan** [comment]
Any objections to closing this issue then?

**Comment by bondjimbond** [comment]
Close it and merge!

**Comment by mjordan** [comment]
Already merged by @MarcusBarnes. Thanks both!

**Comment by mjordan** [comment]
Documentation updated in the "The FILE_GETTER section" of https://github.com/MarcusBarnes/mik/wiki/Toolchain:-CSV-single-file-objects" and in https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Generating-metadata-only,-not-content-files.
