### ISSUE TITLE
Sample data "Error with CSV input file"

### ISSUE THREAD

**Issue by jpeak5** [MarcusBarnes/mik#323]
Removing the extra empty line at the end of `tutorial_metadata.csv` fixes the error output below. I do not see anywhere obvious to make a pull request, but might be useful for others...

While getting started on the __CSV Single File toolchain__,

- using the tutorial sample data https://www.dropbox.com/s/30jeudn9cve87k5/mik_tutorial_data.zip?dl=1,
- MIK version https://github.com/MarcusBarnes/mik/commit/3613a3d5ae49a6828d278a4171ce4b2575fa7e4a and 
- running: `./mik --config sample-csv/tutorial_config.ini --checkconfig all`

~~~
root@vagrant-ubuntu-trusty-64:/opt/mik# ./mik --config sample-csv/tutorial_config.ini --checkconfig all
string(39) "/opt/mik/sample-csv/tutorial_config.ini"
string(39) "/opt/mik/sample-csv/tutorial_config.ini"
Commencing MIK.
Mapping snippets are OK
The path /tmp/miktutorial_temp (defined in configuration setting temp_directory) does not exist but will be created for you.
The path /tmp/miktutorial_temp (defined in configuration setting temp_directory) does not exist but will be created for you.
Paths are OK
Input directory paths are OK.
Error with CSV input file: it appears that row 7 does not have the same number of colums (1) as the header row (7).
~~~

**Comment by mjordan** [comment]
@jpeak5, welcome back! We're very happy to see people are using the tutorial!

This issue is related to #321. Since I can't see any problem with MIK's output when there are blank lines in the CSV file, my take on this is that the output of `--checkconfig` is misleading and should be made less so.

However, I might be completely wrong about that. If MIK does produce malformed output when there are empty rows in the CSV I think we should make MIK tolerant of empty rows since they are probably pretty common in the wild. If MIK is tolerant of empty rows in the CSV, we should fix or eliminate the misleading message produced by `--checkconfig`.

@MarcusBarnes and @jpeak5 what do you think of this approach? Happy to discuss further.

Regardless, there is no reason we should not remove that empty line from the tutorial CSV file, which I can take care of.

**Comment by mjordan** [comment]
@jpeak5 and @MarcusBarnes I'm happy to change the output of `--checkconfig` when it encounters in the input CSV to something like 

`Row X in [input file] is empty. This is harmless but we thought you should know it's empty in case it isn't intentional.`

Any objections? Plus I'll remove the blank row from the tutorial input file.

**Comment by jpeak5** [comment]
For sure, that sounds good, @mjordan

**Comment by mjordan** [comment]
I've removed the empty line from the tutorial metadata and uploaded the fixed .zip file. Will move on to the `--checkconfig` work next.

**Comment by mjordan** [comment]
I've added a check to see if rows in the CSV input file are empty; if `--checkconfig` encounters an empty row (in this case, row 6), it will report: 

`Row 6 in the CSV input file appears to be empty; this is OK, just reporting it in case it's unintentional.`

Will open a PR.

**Comment by mjordan** [comment]
Full output of `--checkconfig`:

```
./mik -c /tmp/mik_tutorial_data/tutorial_config.ini --checkconfig all
Commencing MIK.
Mapping snippets are OK
The path /tmp/miktutorial_temp (defined in configuration setting temp_directory) does not exist but will be created for you.
The path /tmp/miktutorial_temp (defined in configuration setting temp_directory) does not exist but will be created for you.
Paths are OK
Input directory paths are OK.
Row 6 in the CSV input file appears to be empty; this is OK, just reporting it in case it's unintentional.
CSV input file appears to be OK.
```

**Comment by mjordan** [comment]
@jpeak5 fix has been merged, mind if we close this issue?

**Comment by mjordan** [comment]
@jpeak5 OK to close this issue?

**Comment by jpeak5** [comment]
For sure, Mark; thx much!

jrp

Sent from my iPhone

On Mar 24, 2017, at 12:41 PM, Mark Jordan <notifications@github.com<mailto:notifications@github.com>> wrote:


@jpeak5<https://github.com/jpeak5> OK to close this issue?
