### ISSUE TITLE
Change URLs to images and other files currently hosted on Dropbox

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#340]
Most of the images used in the wiki, and the sample files provided as part of the tutorial, are hosted in my Drupbox account. Dropbox is going to convert public folders to non-public one [on March 15](https://www.dropbox.com/help/16).

I will go through the linked images and change the URLs as documented in the Dropbox help page linked above.

**Comment by mjordan** [comment]
Another option is to host images, etcl. within the MIK Wiki git repo, as @MarcusBarnes suggested. Maybe that's the better way to go, at some added inconvenience since adding new images will require cloning the wiki repo down and editing it.

**Comment by mjordan** [comment]
"Share links" will continue to work. Share links I have created are in the form `https://dl.dropboxusercontent.com/u/1015702/linked_to/MIK_overview_general.png`, i.e., `u/1015702/linked_to`, where 'linked_to' is the folder they are in on my Dropbox space.

I cloned the MIK wiki and then `grepped` through the files for 'dropbox'. All occurrences contain `u/1015702/linked_to`, so perhaps we're OK?

**Comment by MarcusBarnes** [comment]
A similar approach would be to download the Dropbox folder with the images, add the folder and files to the MIK wiki repo, and then update the links in a similar manner.  Then push back up.  Similar to what is outlined in this blog post on how to [add images to GitHub Wikis](http://mikehadlow.blogspot.ca/2014/03/how-to-add-images-to-github-wiki.html). 

We can review on on or after March 15th to see if the current approach worked as expected.  One downside I see is that the wiki is not as self-contained if the images are from Dropbox rather than as part of the wiki repo itself.

**Comment by mjordan** [comment]
Welp, I can confirm that the share links didn't work.

**Comment by MarcusBarnes** [comment]
@mjordan Thank you for confirming.  We can use the approach in the first paragraph of [my earlier comment](Bibliography).

**Comment by mjordan** [comment]
To create a share link for images in Dropbox, in the web client,

1. hover over the filename until the "Share" link appears
1. click on it, then click on "Create a link"
1. click on "Copy link"
1. paste the link into your text editor. It will look like `https://www.dropbox.com/s/2cxnybrhs4o3klr/mik_tutorial_batch_upload.png?dl=0`
1. change the "dl=0" at the end to "dl=1" to avoid Dropbox's advertisement overlay.

**Comment by mjordan** [comment]
OK, I've updated the links in the tutorial. I'll open a PR later today using this issue number for image embedded in the MIK README.

**Comment by mjordan** [comment]
@MarcusBarnes thanks. Should we close this issue? I can continue working on updating the image URLs on the other wiki pages.
