### ISSUE TITLE
Make migrated from URI configurable

### ISSUE THREAD

**Issue by jonathangreen** [MarcusBarnes/mik#450]
Looks like the migrated from URI is currently hard coded to contain `http://content.lib.sfu.ca/cdm/ref/collection/`:
https://github.com/MarcusBarnes/mik/blob/master/src/metadataparsers/mods/CdmToMods.php#L169

Be nice to be able to override that with your own CDM url.

**Comment by mjordan** [comment]
Totally. Sorry we didn't catch this earlier. We already use Twig templates so maybe providing a config option to point to one of is a possible solution.

**Comment by jonathangreen** [comment]
No worries! Just wanted to make a ticket to note it, since i just stumbled upon it. A small twig template makes sense to me.

**Comment by mjordan** [comment]
I think we already have the solution to this problem in https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-InsertXmlFromTemplate. We should just remove the `include_migrated_from_uri` .ini option and document how to add the following snippet:

```xml
 <identifier type="uri" invalid="yes" displayLabel="Migrated From">http://contentdm.example.com/cdm/ref/collection/foo/id/{{ ID  }}</identifier>
```

**Comment by mjordan** [comment]
Note: we would also need to remove https://github.com/MarcusBarnes/mik/blob/master/src/metadataparsers/mods/CdmToMods.php#L163-L172.

**Comment by mjordan** [comment]
@jonathangreen If I opened a PR for this would you be able to test?

**Comment by mjordan** [comment]
Yikes, found #176 while sifting through old issues to close.

**Comment by jonathangreen** [comment]
@mjordan I can close this as a duplicate if you want? I am also willing to test.

**Comment by mjordan** [comment]
@jonathangreen yes please, close this one. I'll pick up the work over at #176. Will have something for you to test this week.

**Comment by jonathangreen** [comment]
Duplicate

**Comment by mjordan** [comment]
@jonathangreen and @MarcusBarnes, looking at this, I'd like to recommend that we create a new metadatamanipulator that uses a Twig template to add the XML fragment to the MODS in the CDM toolchains for the "migrated from" value. The template can take two values, the collection alias and the object or page pointer, both of which are available in the function where the respective MODS is generated. The same template could be used for both the parent and page level fragments. A typical template would look like this:

```xml
<identifier type="uri" invalid="yes" displayLabel="Migrated From">http://contentdm.org.net/cdm/ref/collection/{{ collection_alias }}/id/{{ pointer }}</identifier>
```

This is not as generalized as the InsertXmlFromTemplate manipulator, but I don't think that is suitable for page-level MODS since within `createPageLevelModsXML()` only `$page_pointer` and `$page_title` are available. We already check specifically for the AddUuidToMods manipulator so checking for one more isn't the worst thing we can do. I'd personally like to see more flexibility here for generating custom page-level MODS but without good use cases I'd rather not build that in. If we had some good use cases, however, we should consider doing that.

I'll note that at the time we wrote the CdmToMods metadata parser, we hadn't introduced Twig into MIK. Now that it's there, adding another Twig-based manipulator isn't that hard.

In the .ini file, we'd deprecate `include_migrated_from_uri` and instead register the new metadata manipulator  like any other, in the `[MANIPULATORS]` section.

Thoughts?

**Comment by mjordan** [comment]
[sorry, I posted a comment here that was meant for #176. I then deleted it and posted it there :face_with_head_bandage: ]
