### ISSUE TITLE
Fetcher Manipulator to target a subset of a CdmNewspaper collection

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#64]
For large collections with large files, it may be desirable to target subsets of a larger newspaper collection.  For example, the ability to process one year of newspaper issues at a time.  The fetcher manipulator functionality created by @mjordan demonstrates how to filter fetched records for the CsvSingleFile toolchain (for example https://github.com/MarcusBarnes/mik/blob/master/src/fetchermanipulators/CsvSingleFileByFilename.php).  Two things must be done to have the CdmNewspaper toolchain use fetcher manipulators to filter fetched records using fetcher manipulator classes:

1. The  determineObjItems and getIssueMasterFiles methods (and any others that are relevant) should be moved from the filegetters/CdmNewspaper.php class to a new fetcher/CdmNewspapers.php class that extends the fetcher/Cdm.php class.

2.  Once this has been done, create a CdmNewspaperByDate fetcher manipulator that would filter fetched records using a supplied regex supplied as a parameter to the named fetcher manipulator in the configuration file.

**Comment by MarcusBarnes** [comment]
Initial work on this feature request is in the following branch: https://github.com/MarcusBarnes/mik/tree/CdmNewspaperFetcherManipulator

**Comment by MarcusBarnes** [comment]
I'd like to compare the performance between master and https://github.com/MarcusBarnes/mik/tree/CdmNewspaperFetcherManipulator before merging into master (or issuing a pull request).

**Comment by mjordan** [comment]
It would be easy to write a fetcher manipulator similar to the new RandomSet that takes in a list of record keys (instead of a randomly generated list) and to limit the items processed by MIK to just those. Might be useful if a job ran but skipped some problematic items; after the problems were fixed, rerun the job using their record keys as input. The path to the list of keys could be passed in as the manipulator's parameter. Another use case would be testing/QA: if you wanted to inspect the output for some specific input objects, you could just list their record keys in an input file and run MIK using this fetcher manipulator.

**Comment by MarcusBarnes** [comment]
:thumbsup:

**Comment by mjordan** [comment]
OK, I'll write up this manipulator.

**Comment by mjordan** [comment]
@MarcusBarnes can we close this one?

**Comment by MarcusBarnes** [comment]
The SpecificSet fetcher manipulator that @mjordan contributed as an outgrowth of discussions on this issue is slightly different than what was originally envisioned.  That said, let's close this issue for now and reopen should we require the ability to fetch specific date range of things such as newspapers.
